### ISSUE TITLE
Character en/decoding issue

### ISSUE THREAD

**Issue by levocky** [calmjm/tojota#17]
Great project!
I had an issue related to character en/decoding for file write/read operations:

 __File "tojota.py", line 109, in _write_file_
    f.write(contents)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u011b' in position 86: character maps to <undefined>_

This issue has been solved (in my case) by adding parameter encoding="utf-8" to function open in line 93 and 108.

**Comment by calmjm** [comment]
Enforced encoding to be utf-8 in https://github.com/calmjm/tojota/pull/22.
