### ISSUE TITLE
Help needed on get statistics

### ISSUE THREAD

**Issue by Herbert-B** [calmjm/tojota#27]
Hi, great job with python api.
I converted succesfully your code to google script.
All function is ok and work perfectly.
Only one have a problem.
When I try to get statistics with url='https://myt-agg.toyota-europe.com/cma/api/v2/trips/summarize' I pass heders and  parameters but in every time I get error "message":"Required String parameter 'from' is not present","errorCode":"CMA400"}
This is my code : 
  params = { 'from': '2021-01-10', 'calendarInterval': 'day'}
  headers = { 'Cookie': 'iPlanetDirectoryPro='+user.token+'','uuid': user.customerProfile.uuid,'VIN': logej.vin}
  //var headers_j = JSON.stringify(headers);
  //var payload = JSON.stringify(params);
  //Logger.log (payload)
  var options = {
    "method": "GET",
    "contentType": "application/json",
    "headers":headers,
    "params":params,
    "muteHttpExceptions": false,
  };
  var statistic=UrlFetchApp.fetch(url, options)

I try to substitute "params" with "from" but have same result error.
Have you any idea about that ? 
When I run the function in python all is ok.
Many thanks for your replay.
Best regards.
Herbert

**Comment by Herbert-B** [comment]
Hi,
no problem , I have "debug" post and from is a parameter of url
I find the correct request.
![Capture](https://user-images.githubusercontent.com/62649710/107511688-1a01c980-6ba6-11eb-8583-5411e0e7892b.PNG)
Thanks.
Herbert

**Comment by calmjm** [comment]
Most probably you weren't putting those params as url query part. Good that you got that working.
