### ISSUE TITLE
CronJob

### ISSUE THREAD

**Issue by stmb-100** [calmjm/tojota#30]
Hello 
could you please add an example of a cronjob. Unfortunately, I am not able to start the script automatically every 30 minutes

**Comment by amalonso** [comment]
Hello,
Mine is this (every hour):
```cron
0 * * * * cd /home/pi/tojota && /home/pi/tojota/venv/bin/python /home/pi/tojota/tojota.py
```
You must know it's on raspberry, I'm cloned the repo on /home/pi/tojota, and create a virtualenv to install requirements:
```bash
git clone https://github.com/calmjm/tojota
cd tojota
virtualenv -p python3 venv
source venv/bin/activate
pip install -r requirements.txt
```
