### ISSUE TITLE
New format of request for toyota services

### ISSUE THREAD

**Issue by roroby1980** [calmjm/tojota#37]
look that toyota change something in the request of the service , i got this error:

2022-03-22 09:40:51,573:__main__:INFO: Get odometer info...
Traceback (most recent call last):
  File "/home/pi/toyota/tojota/tojota.py", line 472, in <module>
    sys.exit(main())
  File "/home/pi/toyota/tojota/tojota.py", line 405, in main
    odometer, odometer_unit, fuel_percent, fresh = myt.get_odometer_fuel()
  File "/home/pi/toyota/tojota/tojota.py", line 234, in get_odometer_fuel
    raise ValueError('Failed to get data {} {} {}'.format(r.text, r.status_code, r.headers))
ValueError: Failed to get data {"timestamp":1647938451655,"status":400,"error":"Bad Request","message":"X-TME-APP-VERSION not provided","errorCode":"CMA400"} 400 {'Content-Type': 'application/json;charset=utf-8', 'ID': '5cb0c17d-4b9a-46d1-8aec-9c9ec0871339', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true', 'Date': 'Tue, 22 Mar 2022 08:40:51 GMT', 'Connection': 'close', 'Strict-Transport-Security': 'max-age=86400'}

can someone go trought this and change the request ?

**Comment by calmjm** [comment]
Partial fix in https://github.com/calmjm/tojota/pull/38

**Comment by Paxy** [comment]
Line: 
`headers = {'Cookie': f'iPlanetDirectoryPro={token}', 'X-TME-APP-VERSION': '4.10.0', 'UUID': uuid.uuid4()}`
Produce headers: 
`{'Cookie': 'iPlanetDirectoryPro=CTYp1MMgpO1C0cuHiyrESFsa7I8.*AAJTSQACMDMAAlNLABxTYlNJSnlUOU9XdHF5c0VjRk1VTU9EOERjb3M9AAR0eXBlAANDVFMAAlMxAAIwMQ..*', 'X-TME-APP-VERSION': '4.10.0', 'UUID': UUID('d50c76e2-6c1d-49a9-829f-070c6a4caf13')}`

Replacing it with:
`headers = {'Cookie': f'iPlanetDirectoryPro={token}', 'X-TME-APP-VERSION': '4.10.0', 'UUID': str(uuid.uuid4())}`
Produce:
`ValueError: Failed to get data {"timestamp":1648808592956,"status":401,"error":"Unauthorized","message":"Token provided in the header is invalid","errorCode":"CMA401"} 401 {'Content-Type': 'application/json;charset=utf-8', 'ID': '9cb22448-51e3-4e14-8dfb-6930edc0b479', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true', 'Content-Length': '136', 'Date': 'Fri, 01 Apr 2022 10:23:12 GMT', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=86400'}`

If the cookie is right, why are we getting Unauthorized?

**Comment by Paxy** [comment]
Hmm, ok, i gone look into using their web app to map required headers and web calls.

**Comment by Paxy** [comment]
> @Paxy well that's the question? I tried using a proxy to inspect the traffic but they've implemented certificate pinning so there is really no way to look at the traffic. Maybe what we are seeing is not the actual problem - maybe other headers are missing and the error message is misleading as it doesn't make sense to use different tokens in the same app IMHO.

I was trying hard to intercept HTTPS protocol, just to find out that it was simple error in get_odometer_fuel class.
UUID is not defined in the class, but fetched random UUID by UUID class.
This lines resolves the issue:
`uuid = self.user_data['customerProfile']['uuid']
 headers = {'Cookie': f'iPlanetDirectoryPro={token}', 'X-TME-APP-VERSION': '4.10.0', 'UUID': uuid}`

**Comment by calmjm** [comment]
Fixed in https://github.com/calmjm/tojota/pull/40
